### ISSUE TITLE
Setup repository

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#1]
**Story**
As a developer, I want a dedicated and properly structured code repository for the Napari Segmenter plugin so that I can contribute to the project

**A/C**
I know this is done when...

- Project repository exists in Github in the proper organization
- All main contributors have read and write access to the repository
- Dev / Engineering leads have administrative access to the repository
- Repository is visible to the public
- `main` branch exists and is protected against deletion and forced pushes
- Pushes to the `main` branch can only happen through pull requests approved by at least 2 reviewers

**Details**

- Setup as private repository for now, in `AllenCell` organization
- Scope for this story is only repository setup - setting up python packaging or CICD is out of scope

**Comment by heeler** [comment]
If we are OpenScience/OpenSource why setup a private repo?

**Comment by Aerendel** [comment]
Fixed, we'll start public in `AllenCell` org

**Comment by heeler** [comment]
I think we've completed all these pieces? Have I missed anything?

**Comment by Aerendel** [comment]
Yup we are all good. I'll close it.
