### ISSUE TITLE
Dynamic workflow engine for classic Segmenter

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#13]
**Story**
As an plugin developer, I want to have a way of representing, displaying and executing classic Segmenter workflow functions so that I can write maintainable and extensible code

**A/C**
I know this is done when...

- I can represent Classic Segmenter workflows, function and function parameters through Python objects
- I can convert/serialize these workflow/function objects into a non binary (human readable) format such as JSON or YAML
- I can dynamically execute Classic Segmenter workflows or individual functions from their object representations
- All available workflows can be successfully run through this engine

**Details**

- Build an engine and necessary API for representing and executing Segmenter workflows so that we do not have to hard-code anything. 
- Goal 1 is to lay the necessary foundation to support planned APP features such as users Creating, Saving and Loading custom workflows
- Goal 2 is to decouple the plugin code from the Segmenter code as much as possible. When breaking code changes happen in Segmenter (ex: functions get renamed, parameters get added or changed, etc.), we do not want to make the same code changes in two different locations
- Goal 3 is to provide maximum flexibility for Segmenter and the plugin to evolve. For example, minimizing the amount of development required to add new functions to existing workflows, or to add entirely new workflows
- This is foundational / core functionality that could be reused outside of the Napari plugin so it most likely should live in the `aicssegmentation` code base
- Initially put huge focus on the API (how we interact with the Segmenter code from the plugin)

**Comment by yrkim98** [comment]
![image](https://user-images.githubusercontent.com/43979182/111539874-a5cdbf00-872b-11eb-9b71-c05c41ecc973.png)
20/25 workflows can currently run on the engine as it is. Looking to get 25/25 today

**Comment by yrkim98** [comment]
All workflows should now work given a valid json file. I can run 21/25 workflows using the engine
The following workflows do not work:

- `lamp1` : empty json file
- `lmb1_mitotic` : empty json file
- `npm1` : missing a fourth step in the json file
- `son`: empty json file
