### ISSUE TITLE
MPP1.6 - Run LaminB1 full workflow

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#19]
**Story**
As a stakeholder, I want to see a complex workflow running in Napari so that I can identify any potential issues

**A/C:**

- I can run a full Lamin B1 interphase workflow on an image loaded in Napari

**Details:**

- Similar to MPP1.5 which has a full workflow for SEC61B - implement the same for LaminB1 interphase.
- This can be done in a new branch to make things easier and just replace SEC61B to avoid having to create extra screens

**Comment by jxchen01** [comment]
We can try lamin b1 interphase workflow. It is one of the complicated ones. 

https://github.com/AllenCell/aics-segmentation/blob/feature/json_workflow/aicssegmentation/structure_wrapper_config/conf_lmnb1_interphase.json

**Comment by jxchen01** [comment]
here is the code:

```
aicssegmentation.core.pre_processing_utils
```
