### ISSUE TITLE
Hard-coded UI for page 6

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#20]
**Story**
As a designer, I want access to UI prototypes viewable in Napari so that I can fine tune the design

**A/C**
I know this is done when...

- Hard-coded version of the "Segmenter Workflow Selection" view displayable in Napari

**Details**

- Implement a hard-coded UI only version of https://docs.google.com/presentation/d/15VsNlMm5Jv1NhJRQ4EDw0O_Y4W9AGNGC7yp2qzK1oGw/edit#slide=id.gbd61a3c0b6_1_217
- The goal is to have a starting point for Thao and us to fine-tune the UI.
- This should have no working functionality - only the UI. For UI controls that are backed by data (ex: drop down) just hard code the values.
- Start a new branch for this type of work (ex: `feature/ui-only`)
- This can be the first view displayed when you open the plugin (MPP can go away)

**Comment by schoinh** [comment]
@Aerendel you mentioned this code shouldn't be merged, do you not want a pull request for this issue? 

https://github.com/AllenCell/napari-aicssegmentation/tree/feature/pg-6-ui/napari_aicssegmentation

![image](https://user-images.githubusercontent.com/12690133/111012086-83652b80-8350-11eb-8396-23ed4ab558b7.png)

**Comment by Aerendel** [comment]
@schoinh let's have a pull request so we can review and ask questions about the code + review screenshots and leave feedback. You can either create a "Draft Pull Request" (recommended) or label your PR "DO NOT MERGE"
