### ISSUE TITLE
[Segmenter-core] json workflow support

### ISSUE THREAD

**Issue by jxchen01** [AllenCell/napari-aicssegmentation#22]
Goal:
1. Each workflow can be defined and implemented as a json file
2. A workflow defined by a json file can be easily applied on an image to generate segmentation
3. Automatically pull all available workflows
4. Provide a comprehensive definition of all functions needed for json workflows, including module name, parameter definition (data type, widget type, data range, etc..)

NOTE:
JSON is not the only way to define a workflow. Advanced users still have the power to implement any workflow in python and used inside Segmenter. To make a workflow available in the plugin as a JSON config file, all functions used in this workflow have to be "streamlinable", which may require implementation of new wrappers. Here, our goal is to make all current workflows in look-up-table available as JSON file, which will require new wrappers or adjusting current wrappers.

**Comment by Aerendel** [comment]
Pending full final verification of all workflows / parameters
