### ISSUE TITLE
Workflow selection - Warn user when no 3D image is loaded

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#28]
**Story**
As a segmenter plugin user, I want to have access to available image channels and segmenter workflows so that I can start processing my data

**A/C**
I know this is done when...
- Given I am on the "Select workflow" screen
  And no image is loaded in Napari (ie. no layers available)
  Then I can see a warning message asking me to load a 3D image

- Given I am on the "Select workflow" screen
  And I have an image loaded 2D Napari (ie. less than 3 dimensions)
  Then I can see a warning message asking me to load a 3D image
  
- Given I am on the "Select workflow" screen  
  When I remove all layers from the Napari viewer
  Then I can see a warning message asking me to load a 3D image  

**Details**
- We want to detect missing or incompatible images and warn the user. The plugin requires at least one 3 dimensional image (meaning at least 3 dimensions X, Y and Z available) to be loaded.
- Warning should be displayed at the top of the plugin widget
- Might be worth looking into designing/styling a standard "Warning label" widget that we can reuse
- See https://docs.google.com/presentation/d/1zQ41ih3b3CzFrYqbT96phuEGq5Y8mrzo_MDHkLfE7Dg for wireframes

**Comment by schoinh** [comment]
The reusable warning label widget will be part of my PR revisions ("page 6" UI) 🙂
