### ISSUE TITLE
UI - Build collapsable box Widget

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#31]
**Story**
As a Segmenter plugin developer, I want reusable UI components so that I can develop more efficiently

**A/C**
I know this is done when...
- I have access to a custom "Expand / Collapse" box PyQT Widget 
- The widget allows me to collapse (hide) the contents of the box manually and programmatically
- The widget allows me to expand (show) the contents of the box manually and programmatically

**Details**
- Needs to collapse / expand on user click 
- Needs to be collapsed / expanded programmatically
- See https://docs.google.com/presentation/d/1zQ41ih3b3CzFrYqbT96phuEGq5Y8mrzo_MDHkLfE7Dg for design. Examples of this can be found on the "Workflow steps" page

**Comment by schoinh** [comment]
I think this needs the FPP label?
