### ISSUE TITLE
Segmenter engine - Support workflow function categories 

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#33]
**Story**
As an plugin developer, I want to have a way of representing, displaying and executing classic Segmenter workflow functions so that I can write maintainable and extensible code

**A/C**
I know this is done when...

- Using the object representation of a workflow and its steps, I can identify the processing category of a given workflow function related to the workflow (ie. Preprocessing, Core, Post-processing, etc.)

**Details**
- We need to know if a function is Pre-processing, Core or Post-processing
- This should be tagged in the json configuration, and available in the object model

**Comment by jxchen01** [comment]
two examples are added: 
for sec61b: https://github.com/AllenCell/aics-segmentation/blob/feature/json_workflow/aicssegmentation/structure_wrapper_config/conf_sec61b.json
for laminb1_interphase: https://github.com/AllenCell/aics-segmentation/blob/feature/json_workflow/aicssegmentation/structure_wrapper_config/conf_lmnb1_interphase.json

**Comment by schoinh** [comment]
This is done, no?
