### ISSUE TITLE
Workflow selection - Layer selection

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#34]
**Story**
As a segmenter plugin user, I want to have access to available image channels and segmenter workflows so that I can start processing my data

**A/C**
I know this is done when...
- Given I am on the "Select workflow" screen
  And I have an image loaded in Napari
  Then I can see all available layers in a selectable list
- Given I am on the "Select workflow" screen
  And I have an image loaded in Napari
  When I add or remove a layer in the Napari viewer
  Then the layer list is updated to reflect the state of the viewer
  
**Details**
- Display available a list of all the layers currently available in the Napari viewer
- For this we will need to hook up to Napari viewer events, this can be done by connecting to `napari.Viewer.events` properties
- See https://docs.google.com/presentation/d/1zQ41ih3b3CzFrYqbT96phuEGq5Y8mrzo_MDHkLfE7Dg for wireframes

**Comment by schoinh** [comment]
This looks like a duplicate of #38 and #24

**Comment by Aerendel** [comment]
Yup it's a duplicate of 38. 24 is the channel, not the layer. Closing this.
