### ISSUE TITLE
Workflow steps - Display selected workflow steps

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#40]
**Story**
As a segmenter plugin user, I want to access and run Segmenter workflow processing steps so that I can produce Segmentations

**A/C**
I know this is done when...
- Given I have a selected Workflow
  And I am on the Workflow Steps screen
  Then I can see all processing steps for the selected Workflow
  And steps are ordered by processing order
  And steps are categorized
  And I can see input controls for the parameters of each workflow step
  And input values are pre-populated with the step's default recommended parameter values

**Details**
- Dynamically display workflow steps for the selected workflow
- Steps should have number, a title, editable input parameters, be properly ordered and be properly categorized (pre-processing, core or post-processing). See https://docs.google.com/presentation/d/1zQ41ih3b3CzFrYqbT96phuEGq5Y8mrzo_MDHkLfE7Dg for latest UI/UX details.
- Since number and step details varies depending on the workflow - this will be better achieved with a reusable "Workflow step" widget. This story depends on completion of such a widget (covered in issue #43 )
- Input values should be defaulted to the recommended defaults provided by the workflow engine

**Comment by schoinh** [comment]
I just noticed in our [json files](https://github.com/AllenCell/aics-segmentation/pull/19/files) that most workflow steps lack a `category` (pre-processing, core, post-processing). The only workflow I've found where all the steps have a category is the sec61-b workflow. I also have other questions about the json data that I detailed in [this PR comment](https://github.com/AllenCell/aics-segmentation/pull/36#pullrequestreview-623777306). I think all of these questions need to get resolved for this ticket. Is there another set of json data somewhere that I missed? @benjijamorris @jxchen01
