### ISSUE TITLE
UI - Build reusable workflow step widget

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#43]

**Comment by schoinh** [comment]
Is this like a wrapper for the collapsible box widget?

**Comment by Aerendel** [comment]
I think the collapsible box widget is just the basic Widget, but then we need a complex user control / Widget to handle dynamically building and displaying a box for each workflow step. That includes picking the right input widgets for the right parameter types, (and later progress bar, run step button, etc.) and exposing events and data as needed for interacting with all of this. This is just a placeholder for now which is why I didn't write down anything - there's a lot to discuss for this one.
