### ISSUE TITLE
UI - Build reusable slider/spinbox combo widget

### ISSUE THREAD

**Issue by schoinh** [AllenCell/napari-aicssegmentation#46]
## Use Case
As a plugin developer, I need a reusable custom widget that contains a slider and a spinbox that are synced to each other. Qt's QSlider widget only supports integer values, so it needs to be adapted to work with float input and outputs as well.

## Notes
* AGAVE has a [similar Qt widget](https://github.com/allen-cell-animated/agave/blob/master/agave_app/Controls.h) (in C++) we could use for inspiration / borrow from.
* MagicGUI has a FloatSlider we could potentially use if it integrates nicely with rest of our Qt code

## Alternatives
* If we are very short on time, for the FPP, we could consider using a QDoubleSpinBox only instead of a slider + spinbox combo.

@Aerendel FYI

**Comment by Aerendel** [comment]
@schoinh looks like we won't need this story since we are using the magicgui widget?

**Comment by schoinh** [comment]
Right. Maybe down the road we'll get really picky about what the magicgui widget does/doesn't offer but I think that should be a separate ticket if/when we need it.
