### ISSUE TITLE
Setup CICD

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#5]
**Story**
As a developer, I want my code to always be verified and ready to deploy so that I can deliver new features as fast as possible

**A/C**
I know this is done when...

- I can build, package, version and deploy (to Pypi) the plugin project with a single automated process
- When code is pushed to a branch open for pull request, build and unit tests are ran automatically
- When I try to merge code into `main`, the branch must have a successful build, otherwise I cannot merge
- When code is pushed to a branch open for pull request, code coverage report is generated and checked against coverage treshold

**Details**

- Use github actions
- Jackson's or Napari's cookiecutter should have a lot of that already in place
- Might need to setup an access key or something for publishing to public Pypi
- Setup automatic build / testing on push to branch, and successful build status checks on merges
- Versioning should be as straightforward as possible and well documented

**Comment by neuromusic** [comment]
FYI, we're working on a CLI utility to help validate napari plugins.

You can follow the progress and provide feedback at https://github.com/napari/napari-plugin-devtools

**Comment by Aerendel** [comment]
@heeler remaining work is Code coverage
