### ISSUE TITLE
cannot handle the simplest 3D data

### ISSUE THREAD

**Issue by jxchen01** [AllenCell/napari-aicssegmentation#74]
## Description
The plugin will fail at the workflow selection step, if the user simply loads a 3d image. 3D array is probably the simplest form of the data or the most common format users may use for. So, it is important to handle simple 3D images.

## Expected Behavior
the plugin needs to handle both 3d or 4d data.

## Reproduction

https://github.com/AllenCell/napari-aicssegmentation/blob/feature/user-set-parameters/napari_aicssegmentation/core/layer_reader.py#L44

**Comment by schoinh** [comment]
To clarify, by simplest 3D data you mean single-channel 3D images, right?

**Comment by Aerendel** [comment]
@jxchen01 can you send me a good 3D image you've used to test?

**Comment by jxchen01** [comment]
https://drive.google.com/file/d/1NstCG7oFTStXFUCWytry7UePdLO7sSev/view?usp=sharing

a sample data
