### ISSUE TITLE
cannot display enough digits for some parameter values

### ISSUE THREAD

**Issue by jxchen01** [AllenCell/napari-aicssegmentation#75]
## Description
some parameters require 3 digits after zero. 

https://github.com/AllenCell/aics-segmentation/blob/feature/workflow-engine/aicssegmentation/structure_wrapper_config/conf_slc25a17.json#L26

But, it seems like current widgets can only dispaly up to 2 digits

**Comment by schoinh** [comment]
Thanks for catching that! We're using a magicgui widget for the slider rows and I don't think I can customize that at the moment... I just filed an [issue](https://github.com/napari/magicgui/issues/226) with magicgui, so we'll see if it looks like we can get this resolved using magicgui in a reasonable amount of time. If we can't get the level of customization we need with magicgui we might have to just build our own with native Qt widgets in the future. Let us know if this is super urgent

**Comment by tlambert03** [comment]
left a workaround for you at https://github.com/napari/magicgui/issues/226 ... but want to also point out that I recently released a dedicated package for a new QtRangeSlider (with 2+ handles) here: https://github.com/tlambert03/QtRangeSlider ... and I'm adding support for sliders with labels in https://github.com/tlambert03/QtRangeSlider/pull/3 ... so if the only thing you're using magicgui for is the sliders with labels, you may want to just use that directly

**Comment by schoinh** [comment]
2 great options, thank you so much @tlambert03 !
