### ISSUE TITLE
Batch processing - Run batch - Disable when invalid inputs

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#94]
**Story**
As a scientist, I want to execute segmentation workflows on a batch of many files so that I can do real science

**A/C**
- Given I have selected a JSON config file
   And a channel index
   And an input directory
   And an output directory
   Then the "Run batch" button is enabled
- Otherwise, if any field is missing, the "Run batch" button is disabled

**Details**

- Enable / disable "Run batch" button based on status of form
- All 4 inputs should be entered for the button to be enabled. Update status of button as user interacts with the form.

**Comment by yrkim98** [comment]
included in this PR: https://github.com/AllenCell/napari-aicssegmentation/pull/97
